# Generated by Django 3.1.7 on 2021-03-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billprofile', '0001_initial'),
        ('cart', '0001_initial'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('created', 'Created'), ('shipped', 'Shipped'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('refunded', 'Refunded')], default='created', max_length=50)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=20.5, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('bill_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing address+', to='addresses.address')),
                ('billing_profle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billprofile.billingprofile')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('ship_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping address+', to='addresses.address')),
            ],
        ),
    ]
