# Generated by Django 2.0.7 on 2019-06-26 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('created', 'Created'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('refunded', 'Refunded')], default='created', max_length=50)),
                ('shipping_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
    ]
