# Generated by Django 3.1.7 on 2021-03-26 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
