# Generated by Django 3.1.7 on 2021-04-07 17:43

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', tinymce.models.HTMLField(null=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('image', models.URLField(max_length=150)),
                ('arrival_date', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(default=accounts.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
