# Generated by Django 3.1.7 on 2021-04-03 20:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210330_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
