# Generated by Django 3.1.7 on 2021-03-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billprofile', '0001_initial'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='billing_profle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_profile', to='billprofile.billingprofile'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(max_length=120),
        ),
    ]
