# Generated by Django 3.1.7 on 2021-03-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20210314_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
