# Generated by Django 3.1.7 on 2021-04-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=20, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_pic', models.ImageField(upload_to='User/Avatar')),
            ],
        ),
    ]
